### ISSUE TITLE
All layer names should be unique.

### ISSUE THREAD

**Issue by Tahedi1** [albermax/innvestigate#130]
I tested the package methods with **VGG16** and it works. But, I have tested it with trained **InceptionV3** model constructed in separate train script as following:
```
base_model = InceptionV3(include_top=False, weights='imagenet',input_shape = (299,299,3))
x = base_model.output
x = GlobalAveragePooling2D()(x)
x = Dense(1024, activation='relu')(x)
x = Dropout(0.2)(x)
predictions = Dense(nbr_classes, activation='softmax')(x)
model = Model(input=base_model.input, output=predictions)
```
And loaded in visualisation script as following (I based on imagenet_compare_methods.ipynb) :
```
model_path = 'path_of_model'
model_weights_path = 'path_of_model_weights'
model = load_model(model_path)
model.load_weights(model_weights_path)
model = keras.models.Model(model.inputs, model.outputs)
model.compile(optimizer="adam", loss="categorical_crossentropy")
preprocess_f=keras.applications.inception_v3.preprocess_input
color_coding="RGB"
channels_first = keras.backend.image_data_format() == "channels_first"
color_conversion = "BGRtoRGB" if color_coding == "BGR" else None
input_range = (-1,1)
noise_scale = (input_range[1]-input_range[0]) * 0.1
```
I got the following error with iutils.keras.graph.model_wo_softmax function: 
```
Traceback (most recent call last):
  File "imagenet_compare_methods_incepV3.py", line 91, in <module>
    model_wo_softmax = iutils.keras.graph.model_wo_softmax(model)
  File "/home_nfs/brahimim/.conda/envs/mohammed.tf.1.9.0/lib/python3.6/site-packages/innvestigate/utils/keras/graph.py", line 312, in model_wo_softmax
    name=model.name)
  File "/home_nfs/brahimim/.conda/envs/mohammed.tf.1.9.0/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home_nfs/brahimim/.conda/envs/mohammed.tf.1.9.0/lib/python3.6/site-packages/keras/engine/network.py", line 93, in __init__
    self._init_graph_network(*args, **kwargs)
  File "/home_nfs/brahimim/.conda/envs/mohammed.tf.1.9.0/lib/python3.6/site-packages/keras/engine/network.py", line 231, in _init_graph_network
    self.inputs, self.outputs)
  File "/home_nfs/brahimim/.conda/envs/mohammed.tf.1.9.0/lib/python3.6/site-packages/keras/engine/network.py", line 1455, in _map_graph_network
    ' times in the model. '
ValueError: The name "dense_1" is used 2 times in the model. All layer names should be unique.
```
To handle this error I have modified the names of my dense layers and I added this code:
```
model.layers[-3].name='dense1'
model.layers[-1].name='dense_final'
```
These methodes [Input, Gradient] work proprly and  SmoothGrad works but with out of memory warning. But with **Guided Backprop** I got an another error :
```
Traceback (most recent call last):
  File "imagenet_compare_methods_incepV3.py", line 133, in <module>
    a = analyzer.analyze(x_pp)
  File "/home_nfs/brahimim/.conda/envs/mohammed.tf.1.9.0/lib/python3.6/site-packages/innvestigate/analyzer/base.py", line 479, in analyze
    self.create_analyzer_model()
  File "/home_nfs/brahimim/.conda/envs/mohammed.tf.1.9.0/lib/python3.6/site-packages/innvestigate/analyzer/base.py", line 443, in create_analyzer_model
    outputs=analysis_outputs+debug_outputs)
  File "/home_nfs/brahimim/.conda/envs/mohammed.tf.1.9.0/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home_nfs/brahimim/.conda/envs/mohammed.tf.1.9.0/lib/python3.6/site-packages/keras/engine/network.py", line 93, in __init__
    self._init_graph_network(*args, **kwargs)
  File "/home_nfs/brahimim/.conda/envs/mohammed.tf.1.9.0/lib/python3.6/site-packages/keras/engine/network.py", line 231, in _init_graph_network
    self.inputs, self.outputs)
  File "/home_nfs/brahimim/.conda/envs/mohammed.tf.1.9.0/lib/python3.6/site-packages/keras/engine/network.py", line 1455, in _map_graph_network
    ' times in the model. '
ValueError: The name "activation_1" is used 2 times in the model. All layer names should be unique.
```
Please help me to solve this issue.

**Comment by Tahedi1** [comment]
I have printed all layers names (before changing the names of layers dens1 and dens2):

```
input_2
conv2d_1
batch_normalization_1
activation_1
conv2d_2
batch_normalization_2
activation_2
conv2d_3
batch_normalization_3
activation_3
max_pooling2d_1
conv2d_4
batch_normalization_4
activation_4
conv2d_5
batch_normalization_5
activation_5
max_pooling2d_2
conv2d_9
batch_normalization_9
activation_9
conv2d_7
conv2d_10
batch_normalization_7
batch_normalization_10
activation_7
activation_10
average_pooling2d_1
conv2d_6
conv2d_8
conv2d_11
conv2d_12
batch_normalization_6
batch_normalization_8
batch_normalization_11
batch_normalization_12
activation_6
activation_8
activation_11
activation_12
mixed0
conv2d_16
batch_normalization_16
activation_16
conv2d_14
conv2d_17
batch_normalization_14
batch_normalization_17
activation_14
activation_17
average_pooling2d_2
conv2d_13
conv2d_15
conv2d_18
conv2d_19
batch_normalization_13
batch_normalization_15
batch_normalization_18
batch_normalization_19
activation_13
activation_15
activation_18
activation_19
mixed1
conv2d_23
batch_normalization_23
activation_23
conv2d_21
conv2d_24
batch_normalization_21
batch_normalization_24
activation_21
activation_24
average_pooling2d_3
conv2d_20
conv2d_22
conv2d_25
conv2d_26
batch_normalization_20
batch_normalization_22
batch_normalization_25
batch_normalization_26
activation_20
activation_22
activation_25
activation_26
mixed2
conv2d_28
batch_normalization_28
activation_28
conv2d_29
batch_normalization_29
activation_29
conv2d_27
conv2d_30
batch_normalization_27
batch_normalization_30
activation_27
activation_30
max_pooling2d_3
mixed3
conv2d_35
batch_normalization_35
activation_35
conv2d_36
batch_normalization_36
activation_36
conv2d_32
conv2d_37
batch_normalization_32
batch_normalization_37
activation_32
activation_37
conv2d_33
conv2d_38
batch_normalization_33
batch_normalization_38
activation_33
activation_38
average_pooling2d_4
conv2d_31
conv2d_34
conv2d_39
conv2d_40
batch_normalization_31
batch_normalization_34
batch_normalization_39
batch_normalization_40
activation_31
activation_34
activation_39
activation_40
mixed4
conv2d_45
batch_normalization_45
activation_45
conv2d_46
batch_normalization_46
activation_46
conv2d_42
conv2d_47
batch_normalization_42
batch_normalization_47
activation_42
activation_47
conv2d_43
conv2d_48
batch_normalization_43
batch_normalization_48
activation_43
activation_48
average_pooling2d_5
conv2d_41
conv2d_44
conv2d_49
conv2d_50
batch_normalization_41
batch_normalization_44
batch_normalization_49
batch_normalization_50
activation_41
activation_44
activation_49
activation_50
mixed5
conv2d_55
batch_normalization_55
activation_55
conv2d_56
batch_normalization_56
activation_56
conv2d_52
conv2d_57
batch_normalization_52
batch_normalization_57
activation_52
activation_57
conv2d_53
conv2d_58
batch_normalization_53
batch_normalization_58
activation_53
activation_58
average_pooling2d_6
conv2d_51
conv2d_54
conv2d_59
conv2d_60
batch_normalization_51
batch_normalization_54
batch_normalization_59
batch_normalization_60
activation_51
activation_54
activation_59
activation_60
mixed6
conv2d_65
batch_normalization_65
activation_65
conv2d_66
batch_normalization_66
activation_66
conv2d_62
conv2d_67
batch_normalization_62
batch_normalization_67
activation_62
activation_67
conv2d_63
conv2d_68
batch_normalization_63
batch_normalization_68
activation_63
activation_68
average_pooling2d_7
conv2d_61
conv2d_64
conv2d_69
conv2d_70
batch_normalization_61
batch_normalization_64
batch_normalization_69
batch_normalization_70
activation_61
activation_64
activation_69
activation_70
mixed7
conv2d_73
batch_normalization_73
activation_73
conv2d_74
batch_normalization_74
activation_74
conv2d_71
conv2d_75
batch_normalization_71
batch_normalization_75
activation_71
activation_75
conv2d_72
conv2d_76
batch_normalization_72
batch_normalization_76
activation_72
activation_76
max_pooling2d_4
mixed8
conv2d_81
batch_normalization_81
activation_81
conv2d_78
conv2d_82
batch_normalization_78
batch_normalization_82
activation_78
activation_82
conv2d_79
conv2d_80
conv2d_83
conv2d_84
average_pooling2d_8
conv2d_77
batch_normalization_79
batch_normalization_80
batch_normalization_83
batch_normalization_84
conv2d_85
batch_normalization_77
activation_79
activation_80
activation_83
activation_84
batch_normalization_85
activation_77
mixed9_0
concatenate_1
activation_85
mixed9
conv2d_90
batch_normalization_90
activation_90
conv2d_87
conv2d_91
batch_normalization_87
batch_normalization_91
activation_87
activation_91
conv2d_88
conv2d_89
conv2d_92
conv2d_93
average_pooling2d_9
conv2d_86
batch_normalization_88
batch_normalization_89
batch_normalization_92
batch_normalization_93
conv2d_94
batch_normalization_86
activation_88
activation_89
activation_92
activation_93
batch_normalization_94
activation_86
mixed9_1
concatenate_2
activation_94
mixed10
global_average_pooling2d_1
dense_1
dropout_1
dense_2

```

**Comment by albermax** [comment]
How about:
```python
base_model = InceptionV3(include_top=False, weights='imagenet',input_shape = (299,299,3))
x = base_model.output
x = GlobalAveragePooling2D(name='special_name_01')(x)
x = Dense(1024, activation='relu', name='special_name_02')(x)
x = Dropout(0.2, name='special_name_03')(x)
predictions = Dense(nbr_classes, activation='softmax', name='special_name_04')(x)
model = Model(input=base_model.input, output=predictions)
```

**Comment by Tahedi1** [comment]
I will retrain the model as you suggested and I will test the script.
The problem is I have already many trained model and I would like to use them directly. I have examined  all layers names and I found them with differents names. 
I dont understand why this error is appeared.

**Comment by albermax** [comment]
Retraining will not help you, I did also not suggest a that.
If you look I suggested to change the name of the layers before you apply them.

The error appears because Keras does accidentally reuse layer names.

**Comment by Tahedi1** [comment]
Ok, albermax. I will test your proposition.

**Comment by Tahedi1** [comment]
In ordre to modify layers name as you sugested :
```
model.layers[-1].name='special_name_04'
model.layers[-2].name='special_name_03'
model.layers[-3].name='special_name_02'
model.layers[-4].name='special_name_01'
```
But I have the same error:

```
Traceback (most recent call last):
  File "visio_incepV3.py", line 134, in <module>
    a = analyzer.analyze(x_pp)
  File "/home_nfs/brahimim/.conda/envs/mohammed.tf.1.9.0/lib/python3.6/site-packages/innvestigate/analyzer/base.py", line 479, in analyze
    self.create_analyzer_model()
  File "/home_nfs/brahimim/.conda/envs/mohammed.tf.1.9.0/lib/python3.6/site-packages/innvestigate/analyzer/base.py", line 443, in create_analyzer_model
    outputs=analysis_outputs+debug_outputs)
  File "/home_nfs/brahimim/.conda/envs/mohammed.tf.1.9.0/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home_nfs/brahimim/.conda/envs/mohammed.tf.1.9.0/lib/python3.6/site-packages/keras/engine/network.py", line 93, in __init__
    self._init_graph_network(*args, **kwargs)
  File "/home_nfs/brahimim/.conda/envs/mohammed.tf.1.9.0/lib/python3.6/site-packages/keras/engine/network.py", line 231, in _init_graph_network
    self.inputs, self.outputs)
  File "/home_nfs/brahimim/.conda/envs/mohammed.tf.1.9.0/lib/python3.6/site-packages/keras/engine/network.py", line 1455, in _map_graph_network
    ' times in the model. '
ValueError: The name "activation_1" is used 2 times in the model. All layer names should be unique.

```

**Comment by Tahedi1** [comment]
I'm not working with imagnet dataset. For this reason, I'm not using your code. I have already trained a model and I have two files (model.h5, model_weights.h5).

**Comment by Tahedi1** [comment]
I have solved the issue but the problem is analyser is very fast with VGG16 but with inceptionV3 is very slow.

**Comment by albermax** [comment]
Again you are not very specific.
We don't experience those problems. Once compiled the code is typically as fast as a gradient computation.

**Comment by dalia1992** [comment]
> I have solved the issue but the problem is analyser is very fast with VGG16 but with inceptionV3 is very slow.

Could you tell me how you solved it? I'm having the same issue
