### ISSUE TITLE
TypeError: 'function' object is not an iterator --- when using PatternComputer.compute_generator()

### ISSUE THREAD

**Issue by LouisK92** [albermax/innvestigate#149]
Hi, I am facing an error when trying to compute patterns with `compute_generator()`:
`TypeError: 'function' object is not an iterator`
(See my code snippet below.)
I couldn't find a solution for quite some time now :/ I am guessing that `compute_generator()` is not happy with the `pattern_comp_generator`-object. On the other hand that object is of type `<class 'keras_preprocessing.image.directory_iterator.DirectoryIterator'>`... which is an iterator - and from the tracebacks I can not read out _which_ "'function' object" is not an iterator...

### imports
```
import keras
from keras.preprocessing import image
import innvestigate
import innvestigate.utils as iutils
```

### load and prepare a model 
(used a simple relu CNN which was defined with keras' functional api)
```
model = keras.models.load_model('./my_model.hdf5')
model_wo_softmax = iutils.keras.graph.model_wo_softmax(model)
```

### data generator
(in the folder './data/train/' there is a folder for each class with the according .jpg images in it.)
```
def preprocess_input(x):
    return x/255
pattern_comp_datagen = image.ImageDataGenerator(preprocessing_function=preprocess_input)
pattern_comp_generator = pattern_comp_datagen.flow_from_directory('./data/train/',
                                                    target_size=(28,28),
                                                    color_mode='rgb',
                                                    batch_size=32,
                                                    class_mode='categorical',
                                                    shuffle=True
                                                    )
```

### compute pattern
```
pattern_comp = innvestigate.tools.pattern.PatternComputer(model_wo_softmax,
                                                          pattern_type='relu')
patterns = pattern_comp.compute_generator(pattern_comp_generator, 
                                          steps_per_epoch=1500,
                                          verbose=1)
```

**Comment by albermax** [comment]
Hi LouisK92,

sorry to hear.
Did you check this example here https://github.com/albermax/innvestigate/blob/master/examples/train_pattern_imagenet.py?
Why do you have the class_mode set? Does it work if you remove that?

Cheers,
Max

**Comment by LouisK92** [comment]
Thanks for your reply!! 

Ah I incorrectly remembered that **class_mode** would be necessary if the folder hierarchy has several classes, I see that's not the case. Unfortunately, leaving out or setting the class_mode to None still results in the same error. 


I also ran the **train_pattern_imagenet.py** example. At first I get the following error:
```
ValueError: `steps=None` is only valid for a generator based on the 
`keras.utils.Sequence` class. Please specify `steps` or use the 
`keras.utils.Sequence` class.
```
when I set steps=50 the original error occurs at line 138
```
138 patterns = pattern_computer.compute_generator(...
--> TypeError: 'function' object is not an iterator
```
I don't think the complete error traceback helps much, for any case I provide it below.

Btw I am using the following **versions**:
python        3.6.7
tensorflow  2.2.4
keras          1.13.1
and I run scripts with jupyter notebook...
the versions should work fine, right?

Thanks for your help!

### error traceback
```
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.6/dist-packages/keras/utils/data_utils.py", line 626, in next_sample
    return six.next(_SHARED_SEQUENCES[uid])
TypeError: 'function' object is not an iterator
"""

The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
./ in <module>
    171         workers=workers,
    172         use_multiprocessing=use_multiprocessing,
--> 173         verbose=1)
    174 
    175     np.savez("%s_pattern_type_%s_tf_dim_ordering_tf_kernels.npz" %

/usr/local/lib/python3.6/dist-packages/innvestigate/tools/pattern.py in compute_generator(self, generator, **kwargs)
    504         # Compute pattern statistics.
    505         for computer in self._computers:
--> 506             computer.fit_generator(generator, **kwargs)
    507 
    508         # Compute and retrieve the actual patterns.

/usr/local/lib/python3.6/dist-packages/keras/legacy/interfaces.py in wrapper(*args, **kwargs)
     89                 warnings.warn('Update your `' + object_name + '` call to the ' +
     90                               'Keras 2 API: ' + signature, stacklevel=2)
---> 91             return func(*args, **kwargs)
     92         wrapper._original_function = func
     93         return wrapper

/usr/local/lib/python3.6/dist-packages/keras/engine/training.py in fit_generator(self, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
   1416             use_multiprocessing=use_multiprocessing,
   1417             shuffle=shuffle,
-> 1418             initial_epoch=initial_epoch)
   1419 
   1420     @interfaces.legacy_generator_methods_support

/usr/local/lib/python3.6/dist-packages/keras/engine/training_generator.py in fit_generator(model, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
    179             batch_index = 0
    180             while steps_done < steps_per_epoch:
--> 181                 generator_output = next(output_generator)
    182 
    183                 if not hasattr(generator_output, '__len__'):

/usr/local/lib/python3.6/dist-packages/keras/utils/data_utils.py in get(self)
    707                     "`use_multiprocessing=False, workers > 1`."
    708                     "For more information see issue #1638.")
--> 709             six.reraise(*sys.exc_info())

/usr/local/lib/python3.6/dist-packages/six.py in reraise(tp, value, tb)
    691             if value.__traceback__ is not tb:
    692                 raise value.with_traceback(tb)
--> 693             raise value
    694         finally:
    695             value = None

/usr/local/lib/python3.6/dist-packages/keras/utils/data_utils.py in get(self)
    683         try:
    684             while self.is_running():
--> 685                 inputs = self.queue.get(block=True).get()
    686                 self.queue.task_done()
    687                 if inputs is not None:

/usr/lib/python3.6/multiprocessing/pool.py in get(self, timeout)
    668             return self._value
    669         else:
--> 670             raise self._value
    671 
    672     def _set(self, i, obj):

TypeError: 'function' object is not an iterator
```

**Comment by albermax** [comment]
Sorry for the late reply. I was off work.
I will get back to you next week!

**Comment by LouisK92** [comment]
I was working on sth else so I didnt go on searching for a solution, but maybe I come back to using some pattern methods, so I am still interested in finding a solution. 
I was thinking about using another generator (one of that `keras.utils.Sequence` class mentioned in the error of my post from 3rd June, I first mistaked the Sequence class with the keras' Sequential mode, that's why I haven't already tried it.) 
I try the other generator when I find the time to do so and let you know what came out!

**Comment by valentinodavide** [comment]
Hi, are there any updates on this issue? I'm facing exactly the same problem.

If it could be of any help this is my configuration:
- Python 3.6.8
- Keras 2.2.4
- tensorflow 1.13.1

This is a snippet of the code I use (but I'm facing the same problem also with pattern.attribution method):

```python
analyzer = innvestigate.create_analyzer("pattern.net", model)

data_generator = preprocessing.image.ImageDataGenerator(
    preprocessing_function=preprocesses)

train_generator = data_generator.flow_from_directory(
    train_path,
    target_size=target_size,
    batch_size=batch_size)

analyzer.fit_generator(train_generator, steps=2)
```

while the stacktrace is:
```
Traceback (most recent call last):
  File "/home/davide/PycharmProjects/innvestigate-gui/innvestigate-gui/main.py", line 1292, in visualize
    analyzer.fit_generator(train_generator, steps=2)
  File "/home/davide/PycharmProjects/innvestigate-gui/innvestigate-gui/innvestigate/innvestigate/analyzer/base.py", line 295, in fit_generator
    **kwargs)
  File "/home/davide/PycharmProjects/innvestigate-gui/innvestigate-gui/innvestigate/innvestigate/analyzer/base.py", line 258, in fit_generator
    return self._fit_generator(*args, **kwargs)
  File "/home/davide/PycharmProjects/innvestigate-gui/innvestigate-gui/innvestigate/innvestigate/analyzer/pattern_based.py", line 234, in _fit_generator
    verbose=verbose)
  File "/home/davide/PycharmProjects/innvestigate-gui/innvestigate-gui/innvestigate/innvestigate/tools/pattern.py", line 506, in compute_generator
    computer.fit_generator(generator, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training_generator.py", line 181, in fit_generator
    generator_output = next(output_generator)
  File "/usr/local/lib/python3.6/dist-packages/keras/utils/data_utils.py", line 709, in get
    six.reraise(*sys.exc_info())
  File "/usr/lib/python3/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/keras/utils/data_utils.py", line 685, in get
    inputs = self.queue.get(block=True).get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.6/dist-packages/keras/utils/data_utils.py", line 626, in next_sample
    return six.next(_SHARED_SEQUENCES[uid])
TypeError: 'function' object is not an iterator
```

Using `analyzer.fit(x_train)` instead, it works correctly: unfortunately, in this way I can train Pattern.Net and Pattern.Attribution using only few images.

If you need any extra information let me know.
Thanks.
