### ISSUE TITLE
Error/Abort when using neuron_selection_mode="index"

### ISSUE THREAD

**Issue by AlexBinder** [albermax/innvestigate#86]
using tf 1.8, keras 2.2.0, 
innvestigate from git clone, python setup.py develop

i want to make an analysis for class 2.
( no error when a = analyzer.analyze(x)  )
i call    a = analyzer.analyze(x,1) in my code, then

2018-07-11 19:05:29.474699: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-07-11 19:05:30.133331: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1392] Found device 0 with properties: 
name: Tesla P100-PCIE-16GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285
pciBusID: 0000:22:00.0
totalMemory: 15.89GiB freeMemory: 11.23GiB
2018-07-11 19:05:30.133368: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1471] Adding visible gpu devices: 0
2018-07-11 19:05:30.682323: I tensorflow/core/common_runtime/gpu/gpu_device.cc:952] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-07-11 19:05:30.682361: I tensorflow/core/common_runtime/gpu/gpu_device.cc:958]      0 
2018-07-11 19:05:30.682368: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   N 
2018-07-11 19:05:30.682746: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10868 MB memory) -> physical GPU (device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:22:00.0, compute capability: 6.0)
okay
at  0  out of  46
Traceback (most recent call last):
  File "lrpanalyze2c.py", line 234, in <module>
    analyze()
  File "lrpanalyze2c.py", line 230, in analyze
    hmperimg(iming,patchsize,outpath)
  File "lrpanalyze2c.py", line 162, in hmperimg
    a = analyzer.analyze(x,1)
  File "/home/theseus/private/alx/experiments/2018_exp/09072018_hmbreast2/innvestigate/innvestigate/analyzer/base.py", line 381, in analyze
    self.compile_analyzer()
  File "/home/theseus/private/alx/experiments/2018_exp/09072018_hmbreast2/innvestigate/innvestigate/analyzer/base.py", line 340, in compile_analyzer
    outputs=model_output)
  File "/home/binder/virtuals/tf_1p8v2/lib/python3.5/site-packages/Keras-2.2.0-py3.5.egg/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/binder/virtuals/tf_1p8v2/lib/python3.5/site-packages/Keras-2.2.0-py3.5.egg/keras/engine/network.py", line 91, in __init__
    self._init_graph_network(*args, **kwargs)
  File "/home/binder/virtuals/tf_1p8v2/lib/python3.5/site-packages/Keras-2.2.0-py3.5.egg/keras/engine/network.py", line 235, in _init_graph_network
    self.inputs, self.outputs)
  File "/home/binder/virtuals/tf_1p8v2/lib/python3.5/site-packages/Keras-2.2.0-py3.5.egg/keras/engine/network.py", line 1501, in _map_graph_network
    ' times in the model. '
ValueError: The name "input_1" is used 2 times in the model. All layer names should be unique.

**Comment by AlexBinder** [comment]
the mnist selection example runs with me though.
in my code i do:

  model = load_model('./modelstmp/dense121_model_sav.hdf5')

  
  prevout = model.layers[-2].output
  outDense = Dense(2, name='newDense',activation='linear')(prevout)
  checkingModel = Model(model.inputs,outDense)
  wgts = model.layers[-1].get_weights()
  checkingModel.get_layer('newDense').set_weights(wgts)

to get rid of a softmax ...

**Comment by AlexBinder** [comment]
what fixes it for me is (sorry its 2:40 am here ... can do git games tmr):

in base.py
change  -------------------->>
 neuron_indexing = keras.layers.Input(shape=[None], dtype=np.int32)
to -------------------->>
neuron_indexing = keras.layers.Input(shape=[None], dtype=np.int32, name='input_selindex')

**Comment by AlexBinder** [comment]
see merger #87 . so close here
