### ISSUE TITLE
Gradient*Input does not work with neuron_selection_mode="index"

### ISSUE THREAD

**Issue by sebastian-lapuschkin** [albermax/innvestigate#89]
Adding Gradient*Input to the list of methods in `examples/mnist_select_neuron.py` yields an `AttributeError`:

```
Output Neuron 0: Input (0.0641s) Gradient (0.3563s) Deconvnet (0.5039s) Guided Backprop (0.3341s) PatternNet (2.3144s) Gradient*Input Traceback (most recent call last):
  File "examples/mnist_select_neuron.py", line 167, in <module>
    a = analyzer.analyze(x, i)
  File "/home/lapuschkin/Desktop/innvestigate-lrp-wip/innvestigate/innvestigate/analyzer/base.py", line 381, in analyze
    self.compile_analyzer()
  File "/home/lapuschkin/Desktop/innvestigate-lrp-wip/innvestigate/innvestigate/analyzer/base.py", line 341, in compile_analyzer
    tmp = self._create_analysis(model)
  File "/home/lapuschkin/Desktop/innvestigate-lrp-wip/innvestigate/innvestigate/analyzer/relevance_based/relevance_analyzer.py", line 183, in _create_analysis
    model.inputs+[model.outputs[0], ]))
  File "/home/lapuschkin/.local/lib/python3.5/site-packages/keras/engine/base_layer.py", line 503, in __call__
    arguments=user_kwargs)
  File "/home/lapuschkin/.local/lib/python3.5/site-packages/keras/engine/base_layer.py", line 571, in _add_inbound_node
    output_tensors[i]._keras_shape = output_shapes[i]
AttributeError: 'NoneType' object has no attribute '_keras_shape'
```

**Comment by sebastian-lapuschkin** [comment]
branch was develop

**Comment by albermax** [comment]
Similar to https://github.com/albermax/innvestigate/issues/79
